dist: bionic


language: python


branches:
  only:
    - master


matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37


before_install:
  - sudo apt-get install -y tox


script:
  - tox
